import React, { useState, useEffect } from 'react';
import { X, FileText, Loader, Copy, Check } from 'lucide-react';
import { toast } from 'react-toastify';
import { aiAPI } from '../config/aiApi';

const SummarizationModal = ({ isOpen, onClose, content, postTitle }) => {
  const [summary, setSummary] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [wordCount, setWordCount] = useState(0);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (isOpen && content) {
      generateSummary();
    }
  }, [isOpen, content]);

  const generateSummary = async () => {
    if (!content.trim()) {
      toast.error('No content available to summarize');
      return;
    }

    setIsLoading(true);
    setSummary('');
    setWordCount(0);

    try {
      // Strip HTML tags from content for cleaner summarization
      const cleanContent = content.replace(/<[^>]*>/g, '').trim();
      
      const response = await aiAPI.summarizeContent(cleanContent, 200);
      
      if (response.status === 'success') {
        setSummary(response.data.summary);
        setWordCount(response.data.word_count || countWords(response.data.summary));
      } else {
        throw new Error(response.message || 'Failed to generate summary');
      }
    } catch (error) {
      console.error('Summarization error:', error);
      toast.error('Failed to generate summary. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const countWords = (text) => {
    return text.trim().split(/\s+/).filter(word => word.length > 0).length;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      toast.success('Summary copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast.error('Failed to copy to clipboard');
    }
  };

  const resetModal = () => {
    setSummary('');
    setWordCount(0);
    setIsLoading(false);
    setCopied(false);
  };

  const handleClose = () => {
    resetModal();
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-[60] p-4">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-3xl max-h-[80vh] overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b bg-amber-600 text-white">
          <div className="flex items-center space-x-2">
            <FileText className="w-6 h-6" />
            <h2 className="text-xl font-semibold">Post Summary</h2>
          </div>
          <button
            onClick={handleClose}
            className="text-white hover:text-gray-200 transition-colors"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto max-h-[70vh]">
          {/* Post Title */}
          {postTitle && (
            <div className="mb-4">
              <h3 className="text-lg font-medium text-gray-800 mb-2">
                Summarizing: {postTitle}
              </h3>
              <div className="h-px bg-gray-200"></div>
            </div>
          )}

          {/* Loading State */}
          {isLoading && (
            <div className="flex items-center justify-center py-12">
              <div className="text-center">
                <Loader className="w-10 h-10 animate-spin text-amber-600 mx-auto mb-4" />
                <p className="text-gray-600 text-lg">Generating summary...</p>
                <p className="text-gray-500 text-sm mt-2">This may take a few moments</p>
              </div>
            </div>
          )}

          {/* Summary Results */}
          {summary && !isLoading && (
            <div className="space-y-4">
              {/* Summary Stats */}
              <div className="flex items-center justify-between bg-gray-50 rounded-lg p-3">
                <div className="flex items-center space-x-4">
                  <span className="text-sm font-medium text-gray-600">
                    Word Count: <span className="text-amber-600">{wordCount}/200</span>
                  </span>
                  <span className="text-sm text-gray-500">
                    Generated by AI
                  </span>
                </div>
                <button
                  onClick={handleCopy}
                  className="flex items-center space-x-1 px-3 py-1 text-sm bg-gray-200 hover:bg-gray-300 rounded-md transition-colors"
                >
                  {copied ? (
                    <>
                      <Check className="w-4 h-4 text-green-600" />
                      <span className="text-green-600">Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" />
                      <span>Copy</span>
                    </>
                  )}
                </button>
              </div>

              {/* Summary Content */}
              <div className="bg-amber-50 rounded-lg p-6 border-l-4 border-amber-500">
                <h4 className="text-lg font-semibold mb-3 text-amber-800">
                  Summary
                </h4>
                <div className="prose max-w-none">
                  <p className="text-gray-700 leading-relaxed whitespace-pre-wrap text-base">
                    {summary}
                  </p>
                </div>
              </div>

              {/* Regenerate Button */}
              <div className="flex justify-center">
                <button
                  onClick={generateSummary}
                  disabled={isLoading}
                  className="px-6 py-2 bg-amber-600 text-white rounded-lg hover:bg-amber-700 transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed flex items-center space-x-2"
                >
                  <FileText className="w-4 h-4" />
                  <span>Regenerate Summary</span>
                </button>
              </div>
            </div>
          )}

          {/* Error State */}
          {!summary && !isLoading && content && (
            <div className="text-center py-8">
              <FileText className="w-16 h-16 text-gray-300 mx-auto mb-4" />
              <p className="text-gray-500 mb-4">
                Failed to generate summary. Please try again.
              </p>
              <button
                onClick={generateSummary}
                className="px-6 py-2 bg-amber-600 text-white rounded-lg hover:bg-amber-700 transition-colors"
              >
                Try Again
              </button>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="border-t p-4 bg-gray-50">
          <div className="flex justify-between items-center">
            <p className="text-xs text-gray-500">
              Summary limited to 200 words for optimal readability
            </p>
            <button
              onClick={handleClose}
              className="px-4 py-2 text-gray-600 hover:text-gray-800 transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SummarizationModal;